version: '2'

services:
  mongodb:
    image: mongo:3.2.11
    volumes:
      - <path to local mongodb data directory>:/data/db
    restart: always
    networks:
      esnet:
        aliases:
          - mongodb

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - <path to local elasticsearch data directory>:/usr/share/elasticsearch/data
    restart: always
    environment:
      http.host: 0.0.0.0
      transport.host: 0.0.0.0
      discovery.zen.minimum_master_nodes: 1
      cluster.name: elasticsearch
      script.max_compilations_per_minute: 200
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
    networks:
      esnet:
        aliases:
          - elasticsearch

  documentsapi:
    build:
      context: documents-api
    volumes:
      - ./documents-api:/api
    command: python3 api.py
    ports:
      - 5000:5000
    restart: always
    networks:
      esnet:
        aliases:
          - documentsapi

  api:
    build:
      context: api
    ports:
      - 8888:8888
    restart: always
    networks:
      esnet:
        aliases:
          - api

  ui:
    build:
      context: ui
    ports:
      - 80:80
    volumes:
      - ./ui/html:/var/www/site
    restart: always
    networks:
      esnet:
        aliases:
          - ui

networks:
  esnet:
    driver: bridge
